services:
  postgresql:
    image: postgres:14.9-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nesttypeormcrudtemplate
    command:
      [
        'postgres',
        '-c',
        'listen_addresses=0.0.0.0',
        '-c',
        'max_connections=300',
      ]
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
